#!/bin/bash

ipsem=`ipcs -s`
aprev3=""
aprev2=""
aprev=""
for a in $ipsem
do
        if [ $a == "timmer" ]
        then
         ipcrm -s $aprev3
        fi
        aprev3=$aprev2
        aprev2=$aprev
        aprev=$a
done

ipshm=`ipcs -m`
for a in $ipshm
do
        if [ $a == "timmer" ]
        then
         ipcrm -m $aprev3
        fi
        aprev3=$aprev2
        aprev2=$aprev
        aprev=$a
done

ipmsg=`ipcs -q`
for a in $impasse
do
        if [ $a == "timmer" ]
        then
         ipcrm -m $aprev3
        fi
        aprev3=$aprev2
        aprev2=$aprev
        aprev=$a
done
